# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for gemini configurations
Name: jolla-configuration-gemini
Requires:
- pattern:jolla-hw-adaptation-gemini
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

Summary: Jolla Configuration gemini

