# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with UI related packages for gemini configurations
Name: jolla-ui-configuration-gemini
Requires:
- jolla-ambient-z@ICON_RES@
- ambient-icons-closed-z@ICON_RES@

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

Summary: Jolla UI Configuration gemini
